#
#        Title:      tmux.conf
#        Brief:      Configurações principais do Tmux
#        Path:       /home/jkyon/.config/tmux/tmux.conf
#        Author:     John Kennedy a.k.a. jKyon
#        Created:    2026-06-20
#        Updated:    2026-06-20
#        Notes:
#


# No topo do tmux.conf
TMUX_CONF_DIR="$HOME/.config/tmux"

# Carrega módulos (ajuste os paths!)
source "$TMUX_CONF_DIR/conf.d/base.conf"
source "$TMUX_CONF_DIR/conf.d/theme.conf"
source "$TMUX_CONF_DIR/conf.d/keys.conf"
source "$TMUX_CONF_DIR/conf.d/plugins.conf"

# TPM (caminho novo!)
run -b '~/.config/tmux/plugins/tpm/tpm'